# Generated by Django 3.2.7 on 2021-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210912_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='date_of_death',
            field=models.CharField(help_text='Enter a date of death of actor', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='date_of_death',
            field=models.CharField(help_text='Enter a date of death of director', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.CharField(help_text='Enter a date of birth of actor', max_length=10, null=True),
        ),
    ]
