# Generated by Django 3.2.7 on 2021-09-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210913_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(help_text='Choose a date of birth of actor', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Choose a date of death of actor', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='fact',
            field=models.ManyToManyField(blank=True, help_text='Select a fact about this actor', to='catalog.Fact'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.CharField(blank=True, help_text='Enter URL of a photo for actor', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(help_text='Choose a date of birth of director', null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Choose a date of death of director', null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='fact',
            field=models.ManyToManyField(blank=True, help_text='Select a fact about this director', to='catalog.Fact'),
        ),
        migrations.AlterField(
            model_name='director',
            name='photo',
            field=models.CharField(blank=True, help_text='Enter URL of a photo for director', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fact',
            field=models.ManyToManyField(blank=True, help_text='Select a fact about this movie', to='catalog.Fact'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, help_text='Enter URL of a movie poster', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release',
            field=models.DateField(help_text='Choose a date of movie release', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.CharField(blank=True, help_text='Enter a brief description of the movie', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.movie')),
            ],
        ),
    ]
