# Generated by Django 3.2.7 on 2021-09-15 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_auto_20210915_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovie',
            name='date',
            field=models.DateField(help_text='Select a date of adding', null=True),
        ),
        migrations.AddField(
            model_name='favoritemovie',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
