# Generated by Django 3.2.7 on 2021-09-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210915_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votedmovie',
            options={'permissions': (('can_see_all', 'See all votes'),)},
        ),
    ]
