# Generated by Django 3.2.7 on 2021-09-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_votedmovie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedmovie',
            name='date',
            field=models.DateTimeField(help_text='Select a date and time of adding', null=True),
        ),
    ]
