# Generated by Django 3.2.7 on 2021-09-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_votedmovie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.CharField(blank=True, help_text='Enter URL of a movie video', max_length=10000, null=True),
        ),
    ]
