# Generated by Django 3.2.7 on 2021-10-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.CharField(blank=True, help_text='Enter Id of a movie on IMDb', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='kp',
            field=models.CharField(blank=True, help_text='Enter Id of a movie on Kinopoisk', max_length=1000, null=True),
        ),
    ]
