# Generated by Django 3.2.7 on 2021-11-29 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0011_auto_20211011_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a movie country', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a movie genre', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Enter a number of this hall', null=True)),
                ('screen_size', models.CharField(blank=True, help_text='Enter size of screen', max_length=50, null=True)),
                ('vip', models.BooleanField(default=False, help_text='Is this hall VIP?')),
            ],
        ),
        migrations.CreateModel(
            name='NMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a movie title', max_length=200)),
                ('release', models.DateField(help_text='Choose a date of movie release', null=True)),
                ('duration', models.IntegerField(help_text='Enter a movie duration', null=True)),
                ('director', models.CharField(help_text='Enter directors for this movie', max_length=1000)),
                ('actors', models.CharField(help_text='Enter actors for this movie', max_length=1000)),
                ('summary', models.CharField(blank=True, help_text='Enter a brief description of the movie', max_length=1000, null=True)),
                ('kp', models.CharField(blank=True, help_text='Enter Id of a movie on Kinopoisk', max_length=1000, null=True)),
                ('imdb', models.CharField(blank=True, help_text='Enter Id of a movie on IMDb', max_length=1000, null=True)),
                ('poster', models.ImageField(blank=True, help_text='Input a poster of movie', null=True, upload_to='')),
                ('date_start', models.DateField(help_text='Choose a date of rental end', null=True)),
                ('price', models.IntegerField(help_text='Enter a base price for movie', null=True)),
                ('country', models.ManyToManyField(help_text='Select a country for this movie', to='catalog.NCountry')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this movie', to='catalog.NGenre')),
            ],
        ),
        migrations.CreateModel(
            name='NPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Enter a number of this place', null=True)),
                ('vip', models.BooleanField(default=False, help_text='Is this place VIP?')),
            ],
        ),
        migrations.CreateModel(
            name='NSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Enter a date of seance', null=True)),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.nhall')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.nmovie')),
            ],
        ),
        migrations.CreateModel(
            name='NTheatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Enter a theatre address', max_length=1000)),
                ('operating_start', models.CharField(help_text='Enter start of operating time', max_length=1000)),
                ('operating_end', models.CharField(help_text='Enter end of operating time', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_url', models.CharField(blank=True, help_text='Enter a url of QR code', max_length=1000, null=True)),
                ('email', models.CharField(blank=True, help_text='Enter an email (only for guests!)', max_length=100, null=True)),
                ('paid', models.BooleanField(default=False, help_text='Is it paid?')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.nplace')),
                ('seance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.nschedule')),
            ],
        ),
        migrations.CreateModel(
            name='NTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Enter a time', null=True)),
                ('coef', models.DecimalField(decimal_places=2, default=1.0, help_text='Enter a coef for this time', max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='NUserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('date', models.DateTimeField(help_text='Select a date and time of adding', null=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.nmovie')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NTicketUserAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_bonuses', models.IntegerField(help_text='Enter an amount of used bonuses', null=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.nticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nschedule',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ntime'),
        ),
        migrations.CreateModel(
            name='NRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Enter a number of this row', null=True)),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.nhall')),
            ],
        ),
        migrations.AddField(
            model_name='nplace',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.nrow'),
        ),
        migrations.AddField(
            model_name='nhall',
            name='theatre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ntheatre'),
        ),
        migrations.CreateModel(
            name='NBonusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='Enter an amount of bonuses', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
