# Generated by Django 3.2.7 on 2021-11-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20211129_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmovie',
            name='date_end',
            field=models.DateField(help_text='Choose a date of rental end', null=True),
        ),
        migrations.AlterField(
            model_name='nmovie',
            name='date_start',
            field=models.DateField(help_text='Choose a date of rental start', null=True),
        ),
    ]
