# Generated by Django 3.2.7 on 2021-11-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20211129_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntheatre',
            name='operating_end',
            field=models.TimeField(help_text='Enter end of operating time', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntheatre',
            name='operating_start',
            field=models.TimeField(help_text='Enter start of operating time', max_length=1000),
        ),
    ]
