# Generated by Django 3.2.7 on 2021-11-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20211129_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nticket',
            name='place',
        ),
        migrations.AddField(
            model_name='nticket',
            name='place',
            field=models.ManyToManyField(null=True, to='catalog.NPlace'),
        ),
        migrations.AlterField(
            model_name='ntime',
            name='coef',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Enter a coef for this time', max_digits=20),
        ),
    ]
