# Generated by Django 3.2.7 on 2021-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20211129_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmovie',
            name='rating',
            field=models.CharField(help_text='Enter a rating of movie', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='nticket',
            name='place',
            field=models.ManyToManyField(to='catalog.NPlace'),
        ),
    ]
