# Generated by Django 3.2.7 on 2022-01-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20211221_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='nticketuseraddition',
            name='added_bonuses',
            field=models.IntegerField(help_text='Enter an amount of added bonuses', null=True),
        ),
        migrations.AlterField(
            model_name='nmovie',
            name='rating',
            field=models.CharField(choices=[('0+', 'zero'), ('6+', 'six'), ('12+', 'twelve'), ('16+', 'sixteen'), ('18+', 'eighteen')], default='12+', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='NUserVote',
        ),
    ]
