# Generated by Django 3.2.7 on 2022-01-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20220107_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='nticket',
            name='buying_datetime',
            field=models.DateTimeField(help_text='Select a date and time of buying', null=True),
        ),
    ]
