# Generated by Django 3.2.7 on 2022-01-09 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0022_nticket_buying_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='NVIPCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter a name of coefficient', max_length=100, null=True)),
                ('coef', models.DecimalField(decimal_places=1, default=1.0, help_text='Enter a coef', max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='nbonuscard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nhall',
            name='theatre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ntheatre'),
        ),
        migrations.AlterField(
            model_name='nplace',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.nrow'),
        ),
        migrations.AlterField(
            model_name='nrow',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.nhall'),
        ),
        migrations.AlterField(
            model_name='nticketuseraddition',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.nticket'),
        ),
        migrations.AlterField(
            model_name='nticketuseraddition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nuserprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user-pics'),
        ),
    ]
