# Generated by Django 3.2.7 on 2022-01-11 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20220109_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nticket',
            name='buying_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 11, 19, 19, 3, 13695), help_text='Select a date and time of buying', null=True),
        ),
    ]
